services:
  - type: web
    name: addressbook
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx384m"